project:
  type: website

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website:
  title: "docs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Reference"
        file: reference/index.qmd


quartodoc:
  # the name used to import the package you want to create reference docs for
  package: nasem_dairy
  renderer:
    style: markdown
    display_name: relative

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: NASEM_equations
      desc: Functions that contain only equations from the Nutrient Requirements of Dairy Cattle model.

    - subtitle: DMI equations
      desc: ALL DMI equations
      package: nasem_dairy.NASEM_equations.dev_DMI_equations
      contents:
        - calculate_Kb_LateGest_DMIn
        - calculate_An_PrePartWklim
        - calculate_Dt_DMIn_Heif_LateGestInd
        - calculate_Dt_DMIn_Heif_LateGestPen
        - calculate_Dt_NDFdev_DMI
        - calculate_Dt_DMIn_Heif_NRCa
        - calculate_Dt_DMIn_Heif_NRCad
        - calculate_Dt_DMIn_Heif_H1
        - calculate_Dt_DMIn_Heif_H2
        - calculate_Dt_DMIn_Heif_HJ1
        - calculate_Dt_DMIn_Heif_HJ2
        - calculate_Dt_DMIn_Lact1
        - calculate_Dt_DMIn_BW_LateGest_i
        - calculate_Dt_DMIn_BW_LateGest_p
        - calculate_Dt_DMIn_DryCow1_FarOff
        - calculate_Dt_DMIn_DryCow1_Close
        - calculate_Dt_DMIn_DryCow2

        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        # - name: dev_DMI_equations
        #   children: embedded


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



